---
title: "Epibenthic Community Statistics on functional ecology from 5 mile ledge"
date: "2023"
author: "Jared Oviatt"
output:
  # pdf_document: 
  #   toc: yes
  #   keep_tex: yes
  #   fig_height: 6
  #   toc: TRUE
  #   highlight: "tango"
  #   code_folding: "show"
  #   theme: "yeti"
  # html_document:
  word_document
editor_options: 
  chunk_output_type: "console"

---

## Initialize
```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  out.width = "6.5in"
)
```

#### Load libraries
```{r Load libraries, include=FALSE, results='hide'}
library(base)
library(FactoMineR) # MFA
library(heatmaply)
library(lme4)
library(FD)
library(mFD)
library(colordistance)
library(ggdark)
library(ggpubr)
library(ggridges)
#library(ggvegan) # gg plotting vegan
library(reshape2)
# library(psych) # describe
library(ggthemes) # pretty plotting
# library(lubridate) # time e.g. ymd() functions
library(pracma) # movavg()
library(vegan) # community stats
# library(zoo) # rollapply() # using to apply stdev, could use this for mean too
# library(flextable) # alternate to kable
library(tidyverse)


source('./R/jho_functions_041523.R')
```

#### define new functions
```{r functions, include=FALSE, results='hide'}
my_ggsave <- function(filename, plot, 
                      device = 'png',
                      path = './Figs/', 
                      dpi = 360, 
                      units = 'in', 
                      width = 6, 
                      height = 6, 
                      bg = 'white')
{
    ggsave(filename, plot, device = device, path = path, dpi = dpi, units = units, width = width, height = height, bg = bg)
}

is.zero <- function(x){
    return(as.numeric(!!x))
}
```

#### Set gg theme
```{r gg setup, include=FALSE}
ax_text_size <- 10
lab_text_size <- 12

theme_set(theme_few() +
              theme(text = element_text(size = lab_text_size),
                    axis.text = element_text(size = ax_text_size))) # add standardized theme elements
#theme_set(darkmode(theme_few()))


```

#### Save Plots
```{r save plots, eval=FALSE, include=FALSE}

my_ggsave(filename = 'Big_fig.png', fig1)
my_ggsave(filename = 'Trait_space.png', trait_space_plot)
my_ggsave(filename = 'Trait_vectors.png', trait_v_fig)
my_ggsave(filename = 'mfa_vectors.png', mfa_v_plot)
my_ggsave(filename = 'Smooth_ax.png', smooth_axis_plot)
my_ggsave(filename = 'Smooth_pc.png', smooth_pc_plot)
my_ggsave(filename = 'Traits_temp_smooth.png', traits_temp_plot_smooth)
my_ggsave(filename = 'Traits_temp_lm.png', traits_temp_plot_lm)
my_ggsave(filename = 'Traits_temp_slopes.png', traits_temp_slopes_plot)
my_ggsave(filename = 'Traits_time_smooth.png', traits_time_plot_smooth)
my_ggsave(filename = 'Traits_time_lm.png', traits_time_plot_lm)
my_ggsave(filename = 'Walk_plot_comm.png', comm_walk_plot)
my_ggsave(filename = 'Walk_plot_cwm.png', cwm_walk_plot)
my_ggsave(filename = 'Walk_plot_mfa.png', mfa_walk_plot)
my_ggsave(filename = 'Richness.png', rich_plot)
my_ggsave(filename = 'Tax_spread.png', tax_spread_plot)
my_ggsave(filename = 'Fun_spread.png', fun_spread_plot)
my_ggsave(filename = 'mfa_spread.png', mfa_spread_plot)
my_ggsave(filename = 'Trait_influence.png', trait_influence_plot)




```

### Load data
```{r Load Data and format, include=FALSE, results='hide'}
cover_file <- "./Data/Percent_cover.csv"
traits_file <- "./Data/Data_cleaned/x 2024-06-07 traits_5_mile_clean.csv"
meta_file <- "./Data/lacroce_metadata.csv"
temp_file <- './Data/vmileA_bottomwater_temp_09.XX.15-12.XX.2023.csv'
cormp_file <- './Data/CORMP_2016_2017.csv'
par_file <- './Data/PAR.csv'

master_cover <- read.csv(cover_file) %>%
    filter(!is.na(Points))
metadata <- read_csv(meta_file)
traits <- read_csv(traits_file)
temp_raw <- read.csv(temp_file)
cormp_raw <- read_csv(cormp_file)
par_raw <- read_csv(par_file)


```

### Make comm, tax, env, struc matrices
```{r Make matrices, echo=FALSE, results='hide'}
# Make community, environment, struc matrices and distance matrices 
comm <- master_cover %>%
    filter(!is.na(`Image.name`)) %>%
    column_to_rownames(var = 'Image.name') %>%
    select(-Points)/100 # return to percentages 0-1
colnames(comm) <- colnames(comm) %>% 
    str_replace_all("[.]", replacement = " ") %>%
    trimws() 
comm <- comm[,(colnames(comm) %in% traits$Name)]

c <- comm # save untransformed

comm <- asin(sqrt(comm))  # asin transformed

meta <- metadata %>%
    column_to_rownames(var = 'Name') %>%
    select(Date, `Season of Scrapes`, Site, Quad) %>%
    rename(Season = `Season of Scrapes`) %>%
    mutate(across(Season:Site, factor))

#comm <- comm[rownames(meta),]

# report community analyzed and species removed with mean abundance
report_comm <- names(comm) %>% 
    as.data.frame() 
names(report_comm) <- c("Species_used")
# report_comm$Species_original <- names()
# write.csv(report_comm, file = "./Data/community_used.csv")

```

```{r load environmental data , include=FALSE, results='hide'}
temp <- temp_raw %>%
    mutate(Date.Time = mdy_hm(Date.Time),
           Date = date(Date.Time),
           Temp = Temperature..C.) %>%
    select(Date, Temp) %>%
    group_by(Date) %>%
    mutate(Temp = mean(Temp)) %>%
    ungroup() %>%
    unique() %>%
    mutate(Temp_mov = movavg(Temp, n = 14)) %>%
    filter(between(Date, min(meta$Date), max(meta$Date))) %>%
    left_join(rownames_to_column(meta, var = 'Name')) 
# 
# cormp <- cormp_raw %>%
#     mutate(Date_Time = mdy_hm(Date_Time),
#            Date = date(Date_Time),
#            Temp_cormp = (Water_temp_F - 32)*5/9) %>%
#     filter(Sal_qual != 'bad' | is.na(Sal_qual)) %>%
#     select(Date, Temp_cormp, Salinity_ppt, Wind_speed, Wind_direction_from, Wave_ht_ft) %>%
#     group_by(Date) %>%
#     mutate(across(Temp_cormp:Wave_ht_ft, ~ mean(.x, na.rm = T))) %>%
#     ungroup() %>%
#     unique() %>%
#     mutate(across(Temp_cormp:Wave_ht_ft, ~ movavg(.x, n = 14), .names = '{.col}_mov')) %>%
#     filter(between(Date, min(meta$Date), max(meta$Date))) %>%
#     left_join(rownames_to_column(meta, var = 'Name')) 
# 
# par <- par_raw %>%
#     mutate(Date_Time = mdy_hm(Date_Time),
#            Date = date(Date_Time),
#            PAR = TotPAR) %>%
#     select(-Date_Time, -TotPAR) %>%
#     group_by(Date) %>%
#     mutate(PAR = mean(PAR)) %>%
#     ungroup() %>%
#     unique() %>%
#     mutate(PAR_mov = movavg(PAR, n = 14)) %>%
#     filter(between(Date, min(meta$Date), max(meta$Date)))

# add salinity and photoperiod too
env <- temp %>%
    select(Date, Temp, Temp_mov, Name) %>%
    unique() %>%
    # left_join(par) %>%
    # left_join(cormp) %>%
    filter(!is.na(Name)) %>%
    column_to_rownames(var = 'Name')

```

### Make trait space, trait comms
```{r make trait space, echo=FALSE}

trait_space_init <- traits %>%
    mutate(Color_L = L,
           Color_a = a,
           Color_b = b,) %>%
    filter(Complete_but_colorless & !is.na(Color_LAB)) %>%
    select(-Short_Code, -Abund, -Percent_complete, -Complete_but_colorless, -Color_LAB, -L, -a, -b)

# format as factors, ordinal factors
trait_space <- trait_space_init %>%
    mutate(across(Observed_thermal_range:Original_individual, as.factor),
           Height = factor(Height, levels = c('0-10', '10-100', '100-500', '500-1000'), ordered = T),
           Branched = factor(Branched, levels = c('no', 'mid', 'frequent'), ordered = T),
           Shape = factor(Shape, levels = c('encrusting', 'globulose', 'elongate', 'filamentous'), ordered = T),
           Calcified = factor(Calcified, levels = c('no', 'soft', 'flex', 'rigid'), ordered = T)) %>%
           separate(Observed_thermal_range, c('Temp_tmin', 'Temp_tmax'), sep = '-') %>%
    mutate(Temp_tmin = as.numeric(Temp_tmin),
           Temp_tmax = as.numeric(Temp_tmax)) %>%
    column_to_rownames('Name') 


# gower dissimilarity
trait_dist <- trait_space %>%
    #mutate(across(everything(), as.numeric)) %>% #not sure if as numeric is right here
    gowdis()

# PCoA traits
trait_pcoa <- pcoa(trait_dist)
trait_plot <- trait_pcoa$vectors %>% 
    as.data.frame() %>%
    rownames_to_column() 


```

```{r plot spp trait space, echo=FALSE}

# spp first
trait_space_plot <- ggplot(trait_plot, aes(x = Axis.1, y = Axis.2, color = Axis.3)) +
    geom_label(aes(label = rowname), show.legend = T) +
    xlab('PCoA Axis 1') +
    ylab('PCoA Axis 2') +
    scale_color_continuous(name = 'PCoA Axis 3') +
    theme(axis.text = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_text(size = lab_text_size + 2),
          legend.text = element_blank(),
          legend.title = element_text(size = lab_text_size + 2),
          legend.position = 'top')
trait_space_plot

```

```{r comm weighted trait avgs, echo=FALSE}

fcomm <- select(comm, rownames(trait_space))
fcomm$sum = rowSums(fcomm)
fcomm <- subset(fcomm, sum > 0) %>%
    select(-sum)
fmeta <- meta[rownames(fcomm),]

cwm <- jfunctcomp(trait_space, as.matrix(fcomm), CWM.type = 'all') 
# FIX SO THAT TRAIT VALUES ARE APPROPRIATE TYPE

env <- env[rownames(cwm),]

```

```{r check trait correlations, echo=FALSE}

# dummy_traits <- trait_space %>%
#     mutate(across(everything(), ~ as.numeric(.x))) %>%
#     rownames_to_column(var = 'Species')
# 
# cor(dummy_traits) %>%
#     heatmaply_cor()
#pairs(dummy_traits, upper.panel = panel.cor)
# 
# dummy_traits %>%
#     pivot_longer(names_to = 'Trait', values_to = 'Value', cols = !Species) %>%
#     ggplot(aes(x = Trait, y = Value)) +
#     geom_point() +
#     geom_smooth() 
# 
# cor(dummy_traits) %>%
#     heatmaply_cor()
# 
# dummy_trait_values <- trait_space %>%
# 
# cor(cwm) %>%
#     heatmaply_cor()
# 
# #ggpairs(cwm, columns = 1:31)
# 
# cwm_long <- cwm %>%
#     pivot_longer(names_to = 'Trait_value', values_to = 'Value', cols = everything()) %>%
#     separate(Trait_value, sep = '_', into = c("Trait", "Trait_value"), extra = 'merge')
# 
# ggplot(cwm_long, aes(x = Value, fill = Trait_value)) +
#     geom_density(alpha = 0.5, show.legend = F) +
#     facet_wrap( ~ Trait, scales = 'free')


```

### Diversity
```{r diversity, echo=FALSE}

# Functional Diversity
fun_div <- dbFD(trait_space, fcomm, corr = 'cailliez', CWM.type = 'all') %>%
    as.data.frame() %>%
    rownames_to_column(var = 'rowname')

# Taxonomic Diveristy (shannon)
tax_div <- diversity(fcomm, index = 'shannon') %>%
    as.data.frame() %>%
    rename('Shannon' = '.') %>%
    rownames_to_column(var = 'rowname')

rich <- fcomm %>%
    rownames_to_column() %>%
    left_join(rownames_to_column(fmeta)) %>%
    mutate(Month = month(Date, label = T),
           Year = year(Date),
           across(`Oculina arbuscula`:`Zonaria tournefortii`, is.zero)) %>%
    filter(Month %in% c('May', 'Jun', 'Jul', 'Aug', 'Sep'))
rich$Rich <- rowSums(select(rich, `Oculina arbuscula`:`Zonaria tournefortii`))

rich_plot <- ggplot(rich, aes(x = Year, y = Rich, color = factor(Year))) +
    geom_boxplot() +
    facet_wrap(~Month)
rich_plot

alg_tot <- falgae %>%
    mutate(Total_alg = rowSums(falgae)) %>%
    select(Total_alg) %>%
    rownames_to_column()

inv_tot <- finverts %>%
    mutate(Total_inv = rowSums(finverts)) %>%
    select(Total_inv) %>%
    rownames_to_column()

# combo
comb_div <- left_join(fun_div, tax_div) %>%
    left_join(rich) %>%
    left_join(alg_tot) %>%
    left_join(inv_tot) %>%
    select(rowname, Date, Site, Season, Quad, RaoQ, Shannon, Rich) %>%
    mutate(RaoQ = scale(RaoQ)[,1],
           Shanon = scale(Shannon)[,1]) %>%
    pivot_longer(cols = c('RaoQ', 'Shannon'), names_to = 'Index', values_to = 'Value')

fig5 <- ggplot(comb_div, aes(x = Season, y = Value, fill = Index)) +
    geom_boxplot(show.legend = F) +
    scale_x_discrete(labels = c('Fall', 'Wint', 'Spri', 'Summ')) +
    facet_wrap(Index ~ year(Date)) +
    xlab('') +
    ylab('Shannon & RaoQ Diversity') +
    theme(axis.text.y = element_blank(),
          axis.text.x = element_text(size = ax_text_size, hjust = 0.5),
          axis.ticks = element_blank(),
          strip.text = element_blank(),
          axis.title = element_text(size = lab_text_size),
          legend.text = element_blank(),
          legend.title = element_text(size = lab_text_size))
fig5

```

### Bray distances over time
```{r date communities, echo=FALSE}

seasonal_comm <- fcomm %>%
    mutate(Date = fmeta$Date) %>%
    group_by(Date) %>%
    mutate(across(`Oculina arbuscula`:`Zonaria tournefortii`, ~ mean(.x, na.rm = T))) %>%
    ungroup() %>%
    filter(!is.na(Date)) %>%
    unique() %>%
    mutate(Date = as.character(Date)) %>%
    column_to_rownames(var = 'Date')

seasonal_cwm <- cwm %>%
    mutate(Date = fmeta$Date) %>%
    group_by(Date) %>%
    mutate(across(Temp_tmin:Color_b, ~ mean(.x, na.rm = T))) %>%
    ungroup() %>%
    filter(!is.na(Date)) %>%
    unique() %>%
    mutate(Date = as.character(Date)) %>%
    column_to_rownames(var = 'Date')

order_dates <- function(d){
    as.numeric(factor(as.Date(d)))
}

scomm <- vegdist(seasonal_comm) %>%
    as.matrix() %>%
    melt() %>%
    mutate(Diff = order_dates(Var2) - order_dates(Var1)) %>%
    filter(Diff == 1) %>%
    mutate(Date = as.Date(Var2),
           Bray = (scale(value)[,1]),
           #Bray = value,
           Type = 'tax') %>%
    select(Date, Bray, Type)

scwm <- vegdist(seasonal_cwm) %>%
    as.matrix() %>%
    melt() %>%
    mutate(Diff = order_dates(Var2) - order_dates(Var1)) %>%
    filter(Diff == 1) %>%
    mutate(Date = as.Date(Var2),
           Bray = (scale(value)[,1]),
           #Bray = value,
           Type = 'fun') %>%
    select(Date, Bray, Type)
```

### Plots    
```{r plotting set up, echo=FALSE}

plot_cwm <- bind_cols(cwm, meta[rownames(cwm),]) %>%
    pivot_longer(names_to = 'Trait', values_to = 'Abund', cols = Temp_tmin:Color_b) %>%
    mutate(Trait_value = as.character(Trait),
           Trait = case_when(.default = 'no match', 
                             str_detect(Trait_value, 'Height')  ~ 'height', 
                             str_detect(Trait_value, 'Orig')  ~ 'OG', 
                             str_detect(Trait_value, 'Branch')  ~ 'branch', 
                             str_detect(Trait_value, 'Shape')  ~ 'shape', 
                             str_detect(Trait_value, 'Temp')  ~ 'Temp', 
                             str_detect(Trait_value, 'Energy')  ~ 'energy', 
                             str_detect(Trait_value, 'Calcif')  ~ 'calcif', 
                             str_detect(Trait_value, 'Color')  ~ 'color'),
           Trait = as.factor(Trait))  # %>%
    # group_by(Trait) %>%
    # mutate(Abund = (scale(Abund)+1)/2) %>%
    # ungroup()

ef <- envfit(trait_pcoa$vectors, trait_space)
trait_vectors_cat <- ef$factors$centroids %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Trait_value') %>%
    mutate(Trait = case_when(.default = 'no match', 
                             str_detect(Trait_value, 'Height')  ~ 'height', 
                             str_detect(Trait_value, 'Orig')  ~ 'OG', 
                             str_detect(Trait_value, 'Branch')  ~ 'branch', 
                             str_detect(Trait_value, 'Shape')  ~ 'shape', 
                             str_detect(Trait_value, 'Temp')  ~ 'Temp', 
                             str_detect(Trait_value, 'Energy')  ~ 'energy', 
                             str_detect(Trait_value, 'Calcif')  ~ 'calcif', 
                             str_detect(Trait_value, 'Color')  ~ 'color'),
           Trait = as.factor(Trait),
           Axis.1 = scale(Axis.1)[,1],
           Axis.2 = scale(Axis.2)[,1])
#trait_vectors$p <- ef$factors$pvals
#trait_vectors$r <- ef$factors$r

trait_vectors_cont <- ef$vectors$arrows %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Trait_value') %>%
    mutate(Trait = case_when(.default = 'no match', 
                             str_detect(Trait_value, 'Height')  ~ 'height', 
                             str_detect(Trait_value, 'Orig')  ~ 'OG', 
                             str_detect(Trait_value, 'Branch')  ~ 'branch', 
                             str_detect(Trait_value, 'Shape')  ~ 'shape', 
                             str_detect(Trait_value, 'Temp')  ~ 'Temp', 
                             str_detect(Trait_value, 'Energy')  ~ 'energy', 
                             str_detect(Trait_value, 'Calcif')  ~ 'calcif', 
                             str_detect(Trait_value, 'Color')  ~ 'color'),
           Trait = as.factor(Trait),
           Axis.1 = scale(Axis.1)[,1],
           Axis.2 = scale(Axis.2)[,1])

trait_vectors <- bind_rows(trait_vectors_cat, trait_vectors_cont)

```

```{r trait vectors, echo=FALSE}

# add labels for prominent vectors
# HOW TO DO THIS FOR TEMP AND COLOR?
# REDUCE OG CATEGORIES
trait_v_fig <- ggplot(trait_vectors, aes(x = Axis.1, y = Axis.2, color = Trait)) +
    geom_segment(aes(x = 0, y = 0, xend = Axis.1, yend = Axis.2), arrow = arrow(length = unit(2, 'mm'), type = 'closed'), show.legend = T) +
    scale_color_discrete(name = 'Trait category') +
    geom_label(aes(label = Trait_value), show.legend = F) +
    xlab('PCoA Axis 1') +
    ylab('PCoA Axis 2') +
    theme(axis.text = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_text(size = lab_text_size + 2),
          legend.position = 'bottom',
          #legend.text.ali = 'top',
          #legend.title.position = 'bottom',
          legend.title = element_text(size = lab_text_size + 2),
          legend.text = element_text(size = ax_text_size))
trait_v_fig
```

```{r do some plotting, echo=FALSE}
plot_bray <- full_join(scomm, scwm)

sample_dates <- c('2016-06-09', '2017-9-15')

tcs <-
    as.data.frame(mdy(
        c(
            '5/24/16',
            '6/9/2016',
            '9/8/2016',
            '10/18/2016',
            '2/10/2017',
            '6/12/2017',
            '6/29/2017',
            '9/15/2017'
            )))

names(tcs) <- c('Date')

TCs <- tcs %>%
    mutate(Next = lead(Date),
           Num = c(0,1,2,3,4,5,6,7),
           Alt = Num %% 2)

plot_env <- env %>%
    mutate(across(Temp:Temp_mov, ~ scale(.x)[,1])) %>% 
    pivot_longer(Temp:Temp_mov, names_to = 'Var', values_to = 'Value') %>%
    mutate(Var = factor(Var)) %>%
    filter(Var %in% c("Temp_mov", "PAR_mov")) 

fun_plot <- ggplot(plot_cwm, aes(x = Date, y = Abund, color = Trait_value)) + 
    geom_smooth(show.legend = F) + 
    facet_wrap( ~ Trait, ncol = 2, scales = 'free_y')
fun_plot

cplot <- ggplot(plot_bray, aes(x = Date, y = abs(Bray))) + 
    geom_col(aes(fill = Type), position = 'dodge', show.legend = F) +
    geom_smooth(aes(color = Type), show.legend = F, linetype = 2, se = F) +
    scale_x_date(limits = as.Date(sample_dates), date_breaks = '3 months') + 
    ylab('Bray Dissimilarity') +
    xlab('') +
    theme(legend.title = element_blank(),
          legend.text = element_text(size = ax_text_size),
          axis.text = element_blank())
cplot

eplot <- ggplot(plot_env, aes(x = Date, y = Value, color = Var)) +
    geom_line(linewidth = 1) +
    geom_vline(data = meta, aes(xintercept = meta$Date), linetype = 3, color = 'black') +
    scale_x_date(limits = as.Date(sample_dates), date_breaks = '3 months') + 
    scale_color_colorblind(labels = c('Surface PAR', 'Temp (\u00B0C)')) +
    xlab('') + 
    ylab('') +
    theme(legend.position = 'top', 
          legend.title = element_blank(),
          legend.text = element_text(size = ax_text_size),
          axis.text.y = element_blank(),
          axis.text = element_text(size = ax_text_size))
eplot

mplot <- ggplot(TCs) +
    geom_rect(aes(xmin = Date, xmax = Next, ymin = 0, ymax = 1, fill = factor(Alt)), show.legend = F) +
    geom_vline(data = meta, aes(xintercept = meta$Date), linetype = 3, color = 'black') +
    #geom_label(aes(x = as.Date(as.numeric(Date) + as.numeric(Next) / 2), y = 0.5, label = Num), nudge_x = 1) + # added in ppt bc too late to figure it out
    scale_x_date(limits = as.Date(sample_dates), date_breaks = '3 months') + 
    scale_fill_manual(values = c('gray95', 'gray50')) +
    xlab('') + 
    ylab('') +
    theme(legend.position = 'top', 
          legend.title = element_blank(),
          legend.text = element_text(size = ax_text_size),
          axis.text.y = element_blank(),
          axis.text = element_text(size = ax_text_size))
mplot

```

```{r fig 1, echo=FALSE}

fig1 <- ggarrange(eplot, cplot, mplot, ncol = 1, heights = c(3,3,1))
fig1

```


## More plots
```{r pca generation and make plots, echo=FALSE}

# cwm_pcoa <- vegdist(cwm, method = 'euclid') %>%
#     pcoa()
# cwm_pcoa <- cwm_pcoa$vectors %>%
#     as.data.frame() 

cwm_pca_whole <- prcomp(cwm, scale. = T)
cwm_pca <- cwm_pca_whole$x %>%
    as.data.frame()

comm_pcoa_whole <- vegdist(fcomm, method = 'euclid') %>%
    pcoa()
comm_pcoa <- comm_pcoa_whole$vectors %>%
    as.data.frame()
##########
# create an MFA to replace PCoA analysis
##########
mfa_group_nums <- c(2, 4, 4, 3, 4, 4, 7, 3)
mfa_names <- c('temp', 'height', 'shape', 'branched', 'calcified', 'energy', 'OG', 'color')
#mfa_types <- c('s', 'n', 'n', 'n', 'n', 'n', 'n', 's')
cwm_mfa_whole <- MFA(cwm, 
               group = mfa_group_nums,
               name.group = mfa_names
               #type = mfa_types # not using bc the cwm are all abundances
               )
mfa_contrib <- cwm_mfa_whole$group$contrib %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Trait') %>%
    pivot_longer(names_to = 'Dim', values_to = 'Contribution', cols = Dim.1:Dim.5) %>%
    mutate(Dim = factor(Dim, levels = c('Dim.1', 'Dim.2', 'Dim.3', 'Dim.4', 'Dim.5')))
mfa_eig <- cwm_mfa_whole$eig %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Dim') %>%
    mutate(Dim = str_replace(Dim, 'comp ', 'Dim.')) %>%
    filter(Dim %in% c('Dim.1', 'Dim.2', 'Dim.3', 'Dim.4', 'Dim.5'))

# # simple is just easy to interpret
# mfa_simplified <- left_join(mfa_contrib, mfa_eig) %>%
#     group_by(Trait, Dim) %>%
#     mutate(Trait_influence = Contribution * `percentage of variance` / 100) %>%
#     group_by(Trait) %>%
#     mutate(Trait_influence = sum(Trait_influence)) %>%
#     ungroup() %>%
#     select(Trait, Trait_influence) %>%
#     unique()

cwm_mfa<- cwm_mfa_whole$ind$coord %>%
    as.data.frame()

ggplot(mfa_contrib, aes(x = Trait, y = Contribution, fill = Dim)) +
    geom_col(color = 'black', position = 'dodge') 
ggplot(mfa_contrib, aes(x = Trait, y = Contribution, fill = Dim)) +
    geom_col(color = 'black', position = 'stack')
ggplot(mfa_contrib, aes(x = Dim, y = Contribution, fill = Trait)) +
    geom_col(color = 'black', position = 'dodge')
trait_influence_plot <- ggplot(mfa_contrib, aes(x = Dim, y = Contribution, fill = Trait)) +
    geom_col(color = 'black', position = 'stack')

# comm_pca <- prcomp(fcomm, scale. = T)$x %>%
#     as.data.frame()

scale_env <- env %>%
    mutate(across(Temp:Temp_mov, ~ scale(.x)[,1]))

plot_cwm_pca <- cwm_pca %>%
    rownames_to_column() %>%
    left_join(rownames_to_column(env)) %>%
    pivot_longer(starts_with("PC"), names_to = 'PC', values_to = 'Value') %>%
    filter(PC %in% c('PC1','PC2','PC3','PC4')) %>%
    mutate(PC = factor(PC))

plot_cwm_mfa <- cwm_mfa %>%
    rownames_to_column() %>%
    left_join(rownames_to_column(env)) %>%
    pivot_longer(starts_with("Dim"), names_to = 'Dim', values_to = 'Value') %>%
    filter(Dim %in% c('Dim.1','Dim.2','Dim.3','Dim.4')) %>%
    mutate(Dim = factor(Dim))

plot_comm_pcoa <- comm_pcoa %>%
    rownames_to_column() %>%
    left_join(rownames_to_column(env)) %>%
    pivot_longer(starts_with("Axis"), names_to = 'Axis', values_to = 'Value') %>%
    filter(Axis %in% c('Axis.1','Axis.2','Axis.3','Axis.4')) %>%
    mutate(Axis = factor(Axis))

plot_cwm_env <- rownames_to_column(cwm) %>%
    left_join(rownames_to_column(env), by = 'rowname') %>%
    pivot_longer(names_to = 'Trait', values_to = 'Abund', cols = Temp_tmin:Color_b) %>%
    mutate(Trait_value = as.character(Trait),
           Trait = case_when(.default = 'no match', 
                             str_detect(Trait_value, 'Height')  ~ 'height', 
                             str_detect(Trait_value, 'Orig')  ~ 'OG', 
                             str_detect(Trait_value, 'Branch')  ~ 'branch', 
                             str_detect(Trait_value, 'Shape')  ~ 'shape', 
                             str_detect(Trait_value, 'Temp')  ~ 'Temp', 
                             str_detect(Trait_value, 'Energy')  ~ 'energy', 
                             str_detect(Trait_value, 'Calcif')  ~ 'calcif', 
                             str_detect(Trait_value, 'Color')  ~ 'color'),
           Trait = as.factor(Trait)) %>%
    group_by(Date, Trait_value) %>%
    mutate(Mean_abund = mean(Abund)) %>%
    ungroup() %>%
    select(-rowname, -Abund) %>%
    unique() %>%
    group_by(Trait_value) %>%
    mutate(Scaled_abund = scale(Mean_abund),
           Scale_temp = scale(Temp_mov),
           Slope = lm(Scaled_abund ~ Scale_temp)$coefficients[2],
           Confmin = confint(lm(Scaled_abund ~ Scale_temp))[1,1],
           Confmax = confint(lm(Scaled_abund ~ Scale_temp))[1,2]) %>%
    ungroup()

smooth_pc_plot <- ggplot(plot_cwm_pca, aes(x = Date, y = Value, color = PC)) + 
    geom_smooth()
smooth_mfa_plot <- ggplot(plot_cwm_mfa, aes(x = Date, y = Value, color = Dim)) + 
    geom_smooth()
smooth_axis_plot <- ggplot(plot_comm_pcoa, aes(x = Date, y = Value, color = Axis)) +
    geom_smooth()

traits_temp_plot_smooth <- ggplot(plot_cwm_env, aes(x = Temp_mov, y = Mean_abund, color = Trait_value)) +
    geom_smooth(show.legend = F) + 
    #geom_line() +
    facet_wrap(~ Trait, scales = 'free_y')
traits_temp_plot_lm <- ggplot(plot_cwm_env, aes(x = Temp_mov, y = Mean_abund, color = Trait_value)) +
    geom_smooth(method = 'lm', show.legend = F) + 
    #geom_line() +
    facet_wrap(~ Trait, scales = 'free_y')
traits_temp_slopes_plot <- ggplot(plot_cwm_env, aes(x = Slope, xmin = Slope + Confmin, xmax = Slope + Confmax, y = Trait_value, color = Trait)) +
    geom_point(show.legend = F) +
    geom_linerange(show.legend = F) +
    geom_vline(aes(xintercept = 0), linetype = 2) +
    ggtitle("Effect (slope) of Temperature on individual trait values (Temp ~ CWM)") +
    ylab('') +
    theme(axis.text.y = element_text(angle = 30))

traits_time_plot_smooth <- ggplot(plot_cwm_env, aes(x = Date, y = Mean_abund, color = Trait_value)) +
    geom_smooth(show.legend = F) + 
    #geom_line() +
    facet_wrap(~ Trait, scales = 'free_y')
traits_time_plot_lm <- ggplot(plot_cwm_env, aes(x = Date, y = Mean_abund, color = Trait_value)) +
    geom_smooth(method = 'lm', show.legend = F) + 
    #geom_line() +
    facet_wrap(~ Trait, scales = 'free_y')


```

```{r walking plots}

comm_walk <- plot_comm_pcoa %>%
    select(Date, Axis, Value) %>%
    filter(Axis %in% c('Axis.1', 'Axis.2', 'Axis.3')) %>%
    group_by(Date, Axis) %>%
    mutate(Value = mean(Value)) %>%
    ungroup() %>%
    unique() %>%
    pivot_wider(names_from = Axis, values_from = Value) %>%
    mutate(lead_Axis.1 = lead(Axis.1, order_by = Date),
           lead_Axis.2 = lead(Axis.2, order_by = Date),
           lead_Axis.3 = lead(Axis.3, order_by = Date),
           Month = month(Date, label = T),
           Year = factor(year(Date)))


comm_walk_plot <- ggplot(comm_walk, aes(x = Axis.1, y = Axis.2, xend = lead_Axis.1, yend = lead_Axis.2, color = Month)) +
    geom_point(aes(shape = Year)) +
    geom_segment(aes(alpha = Axis.3-lead_Axis.3)) +
    scale_color_discrete()

cwm_walk <- plot_cwm_pca %>%
    select(Date, PC, Value) %>%
    filter(PC %in% c('PC1', 'PC2', 'PC3')) %>%
    group_by(Date, PC) %>%
    mutate(Value = mean(Value)) %>%
    ungroup() %>%
    unique() %>%
    pivot_wider(names_from = PC, values_from = Value) %>%
    mutate(lead_PC1 = lead(PC1, order_by = Date),
           lead_PC2 = lead(PC2, order_by = Date),
           lead_PC3 = lead(PC3, order_by = Date),
           Month = month(Date, label = T),
           Year = factor(year(Date)))

cwm_walk_plot <- ggplot(cwm_walk, aes(x = PC1, y = PC2, xend = lead_PC1, yend = lead_PC2, color = Month)) +
    geom_point(aes(shape = Year)) +
    geom_segment(aes(alpha = PC3-lead_PC3)) +
    scale_color_discrete()

# "Annual community shifts across a functional trait gradient" 
# Same time, different function
# is that just algae <-> inverts ?

mfa_walk <- plot_cwm_mfa %>%
    select(Date, Dim, Value) %>%
    filter(Dim %in% c('Dim.1', 'Dim.2', 'Dim.3')) %>%
    group_by(Date, Dim) %>%
    mutate(Value = mean(Value)) %>%
    ungroup() %>%
    unique() %>%
    pivot_wider(names_from = Dim, values_from = Value) %>%
    mutate(lead_Dim.1 = lead(Dim.1, order_by = Date),
           lead_Dim.2 = lead(Dim.2, order_by = Date),
           lead_Dim.3 = lead(Dim.3, order_by = Date),
           Month = month(Date, label = T),
           Year = factor(year(Date)))

mfa_walk_plot <- ggplot(mfa_walk, aes(x = Dim.1, y = Dim.2, xend = lead_Dim.1, yend = lead_Dim.2, color = Month)) +
    geom_point(aes(shape = Year)) +
    geom_segment(aes(alpha = Dim.3-lead_Dim.3)) +
    scale_color_discrete()


fun_spread_plot <- plot_cwm_pca %>%
    pivot_wider(names_from = PC, values_from = Value) %>%
    mutate(Month = month(Date, label = T),
           Year = year(Date)) %>% 
    filter(Month %in% c('Jul', 'Aug', 'Sep')) %>%
ggplot(aes(x = PC1, y = PC2, color = factor(Year))) +
    geom_point() +
    stat_ellipse() +
    ggtitle('Functional Comm')

mfa_spread_plot <- plot_cwm_mfa %>%
    pivot_wider(names_from = Dim, values_from = Value) %>%
    mutate(Month = month(Date, label = T),
           Year = year(Date)) %>% 
    filter(Month %in% c('Jul', 'Aug', 'Sep')) %>%
ggplot(aes(x = Dim.1, y = Dim.2, color = factor(Year))) +
    geom_point() +
    stat_ellipse() +
    ggtitle('Functional Comm')

mfa_v_plot <- ggplot() +
    geom_point(data = cwm_mfa, aes(x = scale(Dim.1), y = scale(Dim.2)), alpha = 0.4) +
    geom_segment(data = rownames_to_column(as.data.frame(cwm_mfa_whole$group$contrib)), 
                 aes(x = 0, y = 0, xend = scale(Dim.1), yend = scale(Dim.2), color = rowname),
                 arrow = arrow(type = 'closed', length = unit(2, 'mm'))) + 
    geom_label(data = rownames_to_column(as.data.frame(cwm_mfa_whole$group$contrib)), 
               aes(x = scale(Dim.1), y = scale(Dim.2), label = rowname)) + 
    ggtitle('Functional Comm')

tax_spread_plot <- plot_comm_pcoa %>%
    pivot_wider(names_from = Axis, values_from = Value) %>%
    mutate(Month = month(Date, label = T),
           Year = year(Date)) %>% 
    filter(Month %in% c('Jul', 'Aug', 'Sep')) %>%
ggplot(aes(x = Axis.1, y = Axis.2, color = factor(Year), shape = Month)) +
    geom_point() +
    stat_ellipse() +
    ggtitle('Tax Comm')


```

```{r run lmer models}

model_df <- left_join(rownames_to_column(scale_env), rownames_to_column(meta)) %>%
    column_to_rownames(var = 'rowname')

lmer(scale(comm_pcoa$Axis.1) ~ Temp_mov + (1|Site) + (1|Date), data = model_df)
lmer(scale(cwm_pca$PC1) ~ Temp_mov + (1|Site) + (1|Date), data = model_df)

# scaling helped, added Date as rf
# may need to average communities on each date. 
mod1c <- lmer(scale(comm_pcoa$Axis.1) ~ Temp_mov + (1|Site) + (1|Quad) + (1|Date), data = model_df)
mod2c <- lmer(scale(comm_pcoa$Axis.2) ~ Temp_mov + (1|Site) + (1|Quad) + (1|Date), data = model_df)
mod3c <- lmer(scale(comm_pcoa$Axis.3) ~ Temp_mov + (1|Site) + (1|Quad) + (1|Date), data = model_df)
mod4c <- lmer(scale(comm_pcoa$Axis.4) ~ Temp_mov + (1|Site) + (1|Quad) + (1|Date), data = model_df)

mod1t <- lmer(scale(cwm_pca$PC1) ~ Temp_mov +  (1|Site) + (1|Quad) + (1|Date), data = model_df)
mod2t <- lmer(scale(cwm_pca$PC2) ~ Temp_mov +  (1|Site) + (1|Quad) + (1|Date), data = model_df)
mod3t <- lmer(scale(cwm_pca$PC3) ~ Temp_mov +  (1|Site) + (1|Quad) + (1|Date), data = model_df)
mod4t <- lmer(scale(cwm_pca$PC4) ~ Temp_mov +  (1|Site) + (1|Quad) + (1|Date), data = model_df)

mod1c
mod2c
mod3c
mod4c
mod1t
mod2t
mod3t
mod4t

```

```{r prep forest plot}

results <- as.data.frame(matrix(nrow = 6, ncol = 0))

r1c <- summary(mod1c)$coefficients %>%
    as.data.frame() %>% 
    rownames_to_column(var = 'Var') %>%
    mutate(PC = factor(1),
           Type = 'tax')
r2c <- summary(mod2c)$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Var') %>%
    mutate(PC = factor(2),
           Type = 'tax')
r3c <- summary(mod3c)$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Var') %>%
    mutate(PC = factor(3),
           Type = 'tax')
r4c <- summary(mod4c)$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Var') %>%
    mutate(PC = factor(4),
           Type = 'tax')
r1f <- summary(mod1t)$coefficients %>%
    as.data.frame() %>% 
    rownames_to_column(var = 'Var') %>%
    mutate(PC = factor(1),
           Type = 'fun')
r2f <- summary(mod2t)$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Var') %>%
    mutate(PC = factor(2),
           Type = 'fun')
r3f <- summary(mod3t)$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Var') %>%
    mutate(PC = factor(3),
           Type = 'fun')
r4f <- summary(mod4t)$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = 'Var') %>%
    mutate(PC = factor(4),
           Type = 'fun')
results <- bind_rows(r1c, r2c, r3c, r4c, r1f, r2f, r3f, r4f) %>%
    group_by(Var) %>%
    mutate(Estimate = abs(Estimate),
           Std_error = `Std. Error`,
           t_value = `t value`) %>%
    ungroup() %>%
    mutate(PC = factor(PC, levels = c(4,3,2,1)),
           Type = factor(Type)) %>%
    select(-`Std. Error`, -`t value`) %>%
    filter(Var != '(Intercept)') %>%
    filter(PC %in% c(1, 2, 3, 4)) %>%
    mutate(Valid_estimate = Estimate * (Estimate > Std_error),
           Var = if_else(Var == 'PAR_mov', 'Surface PAR', 'Temp (\u00B0C)')) %>%
    group_by(Var, Type) %>%
    mutate(Total_valid_estimate = sum(Valid_estimate)) %>%
    ungroup()

results

```

```{r plot forest plots}
forest_plot <- results %>%
    ggplot(aes(y = PC, x = Estimate, color = Type)) +
    #geom_col(aes(y = Var, x = Total_valid_estimate, fill = Type), color = 'grey25', position = 'dodge') +
    geom_pointrange(aes(xmin = Estimate - Std_error, xmax = Estimate + Std_error), position = position_jitter(width = 0, height = .1, seed = 1), show.legend = F) +
    geom_vline(xintercept = 0, linetype = 2, color = 'black') +
    xlab('Effect Size (slope estimate)') +
    ylab('PCA Axis') +
    scale_color_discrete(name = 'Analysis', labels = c('Functional', 'Taxonomic')) + 
    facet_grid(~ Var) +
    theme(axis.ticks = element_blank(),
          axis.text.y = element_text(size = ax_text_size),
          plot.margin = margin(0,0,8,8),
          strip.text = element_text(size = lab_text_size))
forest_plot
# 
# legend_fig <- results %>%
#     ggplot(aes(y = PC, x = Estimate, fill = Type)) +
#     geom_col() +
#     scale_fill_discrete(name = 'Analysis  ', labels = c('Functional', 'Taxonomic')) + 
#     theme(legend.title = element_text(size = 36),
#           legend.text = element_text(size = 30),
#           legend.key.size = unit(2, 'cm'),
#           legend.position = 'top'#,
#           #legend.key.spacing.x = unit(.25, 'in')
#           )
# legend_fig

# total_plot <- results %>%
#     select(Var, Type, Total_valid_estimate) %>%
#     unique() %>%
#     ggplot(aes(x = Var, y = Total_valid_estimate, fill = Type)) +
#     geom_col(position = position_dodge2()) +
#     xlab('') +
#     ylab('') +
#     scale_fill_discrete(name = 'Analysis', labels = c('Functional', 'Taxonomic')) +
#     facet_wrap(~ Var, scales = 'free_x') +
#     theme(axis.ticks = element_blank(),
#           axis.text = element_text(size = ax_text_size),
#           axis.text.x = element_blank(),
#           legend.title = element_text(size = lab_text_size),
#           legend.text = element_text(size = ax_text_size),
#           plot.margin = margin(0,0,20,8),
#           strip.text = element_text(size = lab_text_size))
# total_plot
# 
# res_combined_plot <- ggarrange(rplot, total_plot, nrow = 1)
# ggarrange(eplot, cplot, res_combined_plot, ncol = 1)

```



